### ISSUE TITLE
TextFormField does not respect flex size on text overflow

### ISSUE THREAD

**Issue by talski** [andyduke/fluid_box#3]
If I enter some big text without spaces, the TextFormField will grow with it, not respecting the flex size

![image](https://user-images.githubusercontent.com/740549/121926023-8125bb00-cd0b-11eb-989a-df52db797357.png)

[Reproduction code](https://gist.github.com/talski/05c864dd53d7c2892aa4736806fe9706)

**Comment by andyduke** [comment]
Yes, I see that the problem is that the TextField returns the minimum required width to accommodate all the entered text, without scrolling.

I will probably have to come up with a different algorithm for calculating the width of the areas that the widgets nested in Fluid can fit into.

I have not yet found how this can be done without several passes and measurements of the width of the child widgets, which is a rather expensive operation.

**Comment by andyduke** [comment]
@talski I have released a fixed version, check if this solved your problem.

**Comment by talski** [comment]
it's working correctly now, thank you for the fast response
